wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.0
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684082387.196918
    t:
      1:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 37
      - 38
      - 41
      - 53
      - 55
      - 80
      3:
      - 13
      - 23
      4: 3.7.0
      5: 0.15.2
      8:
      - 5
