#python3 tools/train.py configs/faster_rcnn/CenterCrop.py 
#python3 tools/train.py configs/faster_rcnn/no_augment.py 
python3 tools/train.py configs/faster_rcnn/normalize.py 
python3 tools/train.py configs/faster_rcnn/ChannelShuffle.py 
python3 tools/train.py configs/faster_rcnn/CLAHE.py 
python3 tools/train.py configs/faster_rcnn/Cutout.py 
python3 tools/train.py configs/faster_rcnn/HorizontalFlip.py 
python3 tools/train.py configs/faster_rcnn/HueSaturation.py 
python3 tools/train.py configs/faster_rcnn/MixUp.py 
python3 tools/train.py configs/faster_rcnn/Mosaic.py 
python3 tools/train.py configs/faster_rcnn/Mul_Resize.py 
python3 tools/train.py configs/faster_rcnn/RandomBrightness.py 
python3 tools/train.py configs/faster_rcnn/RandomResizedCrop.py 
python3 tools/train.py configs/faster_rcnn/RandomRotate90.py 
python3 tools/train.py configs/faster_rcnn/JpegCompression.py 
python3 tools/train.py configs/faster_rcnn/MedianBlur.py 
python3 tools/train.py configs/faster_rcnn/RGBShift.py 
python3 tools/train.py configs/faster_rcnn/VerticalFlip.py 
